CREATE SCHEMA IF NOT EXISTS yate;

CREATE TABLE IF NOT EXISTS yate.login (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE,
    contrasena varchar(255) NOT NULL,
    activo boolean NOT NULL,
    rol varchar(255) NOT NULL CHECK (rol IN ('ADMIN', 'CLIENTE'))
);
CREATE TABLE IF NOT EXISTS yate.cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100),
    apellido varchar(100),
    email varchar(254),
    create_at timestamp(6),
    login_id bigint UNIQUE REFERENCES yate.login(id)
);
CREATE TABLE IF NOT EXISTS yate.producto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    valor_unitario numeric(12,2) NOT NULL,
    stock integer NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS yate.encabezado (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES yate.cliente(id),
    fecha timestamp(6) NOT NULL,
    total numeric(24,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS yate.detalle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encabezado_id bigint NOT NULL REFERENCES yate.encabezado(id),
    producto_id bigint NOT NULL REFERENCES yate.producto(id),
    cantidad integer NOT NULL,
    valor numeric(24,2) NOT NULL
);
